name: Run tests

on:
  workflow_dispatch:
    inputs:
      Marking:
        description: 'marking'
        required: True
        type: choice
        options:
          - profile
      browser:
        description: "Browser"
        required: true
        type: choice
        options:
          - chrome:100.0
          - firefox:97.0
        default: chrome
      base_url:
        description: "URL"
        required: true
        default: "http://nginx:8080/"
        type: string
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: "Set branch env for tests"
        shell: bash
        run: |
          echo "GIT_BRANCH_TESTS=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Checkout test code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GIT_BRANCH_TESTS }}
          path: test

      - name: Build Docker image
        run: docker build -t test/Dockerfile .

      - name: "Create network"
        shell: bash
        run: |
          if [[ -z "$(docker network ls | grep ${{ env.GIT_BRANCH_TESTS }})" ]]; then docker network create --attachable ${{ env.GIT_BRANCH_TESTS }}; fi

      - name: "Create selenoid"
        shell: bash
        run: |
          if [[ -n "$(docker ps -a | grep ${{ env.GIT_BRANCH_TESTS }}-selenoid)" ]]; then docker rm -f ${{ env.GIT_BRANCH_TESTS }}-selenoid; fi
          
          envsubst < ui-test/browser.json > browser.configured.json
          cat browser.configured.json
          docker pull selenoid/${{ github.event.inputs.browser }}
          
          docker run -d --restart always \
                --network ${{ env.GIT_BRANCH_TESTS }} \
                --network-alias selenoid \
                --hostname selenoid \
                --name ${{ env.GIT_BRANCH_TESTS }}-selenoid \
                --volume /var/run/docker.sock:/var/run/docker.sock \
                aerokube/selenoid:latest -conf /browser.json -container-network ${{ env.GIT_BRANCH_TESTS }}
          docker cp ./browser.configured.json ${{ env.GIT_BRANCH_TESTS }}-selenoid:/browser.json
          docker restart ${{ env.GIT_BRANCH_TESTS }}-selenoid
          
      - name: "Run tests"
        shell: bash
        run: |
          mkdir -p ${{ env.ALLURE_FOLDER }}
          docker login ${{ secrets.DOCKER_REG }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          if [[ -n "$(docker ps -a | grep ${{ env.GIT_BRANCH_TESTS }}-test)" ]]; then docker rm -f ${{ env.GIT_BRANCH_TESTS }}-test; fi
          docker run \
            --network ${{ env.GIT_BRANCH_TESTS }} \
            --name ${{ env.GIT_BRANCH_TESTS }}-test \
            bash -c "if [[ '${{ github.event.inputs.marking }}' == 'profile' ]]; then
                       pytest -m 'profile' --remote_browser --browser_name=${{ github.event.inputs.browser }} --base_url=${{ github.event.inputs.base_url }} --alluredir ${{ env.ALLURE_FOLDER }} ;

#


